"""empty message

Revision ID: 9a72d951073b
Revises: 8360117c769f
Create Date: 2023-03-12 18:45:13.818353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a72d951073b'
down_revision = '8360117c769f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('category_cat_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['category_name'])
        batch_op.drop_column('cat_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('category_cat_name_key', ['cat_name'])
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
